travis:
  secure:
    BINSTAR_TOKEN: K+AzP68FXlB5t4qnFPw9YgWEw3LeCAJ4UAb0KOemmMy0Gq+HKDoPyGaGExEV7BbsZuIoUvoKiRFcwqQZV+2KZLObBeGJmZhXbTd2IlafwQt5e+eXUu7sXUUhCWBuhXPopO0it6Xcl3uQFVnAUvnyEIN40+nceed7q7dow1URDPDStVf8rKN5Z1lZAJc4q7PJVvemMHG8GW0hSU6vN8ExrIvQWQXqiQ6DDsRDdqrBLT70Nc5ksXee+y/ezkiHbwVFQzzw7e3dPGo6iXf2vKLcfgyo4/LDYhWCNpM7RiGtv8Ma8lPH3Y5FQ/n6yBgLHffwOqWX3x9grhO/zDhiC04vzUDq2kLA/bWz00uFCs33bjbuMCNKqEyEEixRMHrd2kXr/AjLl9t5HNcKTjWA50fDy6HDMpFlw5bmHqUSf8dkuRaclqVMMj9OtTTMbO/3n9y0DSqaFWr2GAF5G5rhEtC361ta0oSQWFM4wW6uAMKZ5MogJG8qbDe8OPru7IjFMm0Ys4/sIfy6jF016TyFiSUnGYuN9zycrlAy9M5sezuJPdtpycxx70eRJAHVRqZieDV221N2HwP6e/agZV63XVumpFzSeeZCUQE9Np4RWhYDFHGqxXs6WDcf9NyWr0BIOnIYhdCeEfESpy/Jd1DIj7Y1Kt/miNx5RIKC8jx6xs1icBk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
